"""empty message

Revision ID: 821a1471b44d
Revises: 
Create Date: 2025-12-07 17:46:56.790446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821a1471b44d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls_urlshortener',
    sa.Column('original_url', sa.String(length=2048), nullable=False),
    sa.Column('short_code', sa.String(length=10), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_urls_urlshortener')),
    sa.UniqueConstraint('short_code', name=op.f('uq_urls_urlshortener_short_code'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urls_urlshortener')
    # ### end Alembic commands ###
